author = "ARMATAK Team"
mainprefix = "armatak"
name = "ARMA Team Awareness Kit"
prefix = "armatak"

[version]
build = 0
major = 1
minor = 1 
patch = 0

git_hash = 0

[files]
exclude = [
  "source/*",
  "*.png",
  "*.tga",
  "*.psd",
  "*.fbx",
  "*.obj",
]

include = [
  "LICENSE",
  "*.dll",
  "*.so",
  "*.paa"
]

[properties]
author = "ARMATAK Team"
url = "https://github.com/valmojr/armatak"

[hemtt.config]
preset = "Hemtt"

[hemtt.launch.default]
mission = "hearts_and_minds.kunduz_valley"
workshop = [
  "450814997", # CBA_A3
  "463939057", # ACE
  "751965892", # ACRE2
  "2522638637", # ACE Extended Arsenal
  "333310405", # Enhanced Movement
  "2034363662", # Enhanced Movement Rework
  "843577117", # RHSUSAF
  "843425103", # RHSAFRF
  "843632231", # RHSSAF
  "843593391", # RHSGREF
  "1673456286", # 3CB Factions
  "2585568796", # Taliban Forces 2021
  "3030830594", # Western Dusk
  "623475643", # 3den Enhanced
  "2257686620", # Blastcore Murr Edition
  "583496184", # CUP Terrains - Core
  "3078351739", # Kunduz River
  "1858075458", # LAMBS_Danger.fsm
  "1808238502", # LAMBS_Suppression
  "3425368881", # M4A1_URGI
  "2268351256", # Tier One Weapons
  "3073216844", # Tier One Weapons - All NVG Compatible
  "2560276469", # Restrict Markers
]

parameters = [
  "-skipIntro",
  "-noSplash",
  "-showScriptErrors",
  "-debug",
  "-filePatching",
]

[binarize]
exclude = [
  "*.jpg"
]